services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - '3000:3000' # Mapea el puerto 3000 del host al contenedor
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=wallet_db
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    build: 
      context: .
      dockerfile: ./postgres/Dockerfile
    #image: postgres:15
    container_name: db
    restart: always
    ports:
      - '5432:5432' 
    #environment:
    #  POSTGRES_USER: postgres
    #  POSTGRES_PASSWORD: secret
    #  POSTGRES_DB: wallet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: